services:
  - type: web
    name: NAME
    env: python
    plan: free
    region: frankfurt
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn flask_app:app --bind 0.0.0.0:$PORT
    healthCheckPath: /healthz
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0
      - key: TG_TOKEN
        sync: false
      - key: TG_OWNER_ID
        sync: false
      - key: TG_WEBHOOK_SECRET
        sync: false
      - key: TG_FORUM_CHAT_ID
        sync: false
      - key: VK_TOKEN
        sync: false
      - key: VK_GROUP_ID
        sync: false
      - key: VK_CONFIRMATION
        sync: false
      - key: VK_CALLBACK_SECRET
        sync: false
      - key: DATABASE_URL
        sync: false
